version: '3.8'

services:
  postgres:
    image: library/postgres:14
    container_name: backend-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace_db
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - $HOME/PycharmProjects/GitHub/.db_data:/var/lib/postgresql/data

  django-backend:
    restart: always
    container_name: django-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./marketplace:/home/marketbackend/src/app
#      - $HOME/PycharmProjects/GitHub/.media:/home/marketbackend/vol/web/media
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    command: 'python manage.py runserver 0.0.0.0:8000'



volumes:
  .static:
  .db_data:
#  .pgadmin-data: