version: '3.8'

services:
  postgres:
    image: library/postgres:14
    container_name: backend-db
    restart: always
    volumes:
      - $HOME/PycharmProjects/GitHub/.db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

#  pgadmin:
#      image: dpage/pgadmin4:latest
#      container_name: pgadmin_web
#      restart: always
#      environment:
#        PGADMIN_DEFAULT_EMAIL: admin@example.com
#        PGADMIN_DEFAULT_PASSWORD: password
#        PGADMIN_LISTEN_PORT: 80
#      ports:
#        - '8080:80'
#      volumes:
#        - $HOME/PycharmProjects/GitHub/.pgadmin-data:/var/lib/pgadmin
#      links:
#        - 'postgres:pgsql-server'


  django-backend:
    restart: always
    container_name: django-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./marketplace:/home/marketbackend/src/app
#      - $HOME/PycharmProjects/GitHub/.media:/home/marketbackend/vol/web/media
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    command: 'python manage.py runserver 0.0.0.0:8000'



volumes:
  .static:
  .db_data:
#  .pgadmin-data: