# Generated by Django 4.0.2 on 2022-02-22 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('bucket_name', models.CharField(max_length=512)),
                ('format', models.CharField(max_length=16)),
                ('size', models.FloatField()),
                ('file', models.FileField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('bucket_name', models.CharField(max_length=512)),
                ('format', models.CharField(max_length=16)),
                ('size', models.FloatField()),
                ('file', models.FileField(upload_to='videos/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideosProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel')),
                ('video_id', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.PROTECT, to='media.videomodel')),
            ],
            options={
                'db_table': 'videos_products',
            },
        ),
        migrations.CreateModel(
            name='PhotosProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_id', models.ForeignKey(db_column='photo_id', on_delete=django.db.models.deletion.PROTECT, to='media.photomodel')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.productmodel')),
            ],
            options={
                'db_table': 'photos_products',
            },
        ),
    ]
